type Query {
  books: [Book]
  book(id: ID!): Book
}

type Mutation {
  createBook(input: CreateBookInput!): Book!
  updateBook(input: UpdateBookInput!): Book
  deleteBook(id: ID!): Boolean
}

schema {
  query: Query
  mutation: Mutation
}